# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: ğŸ—ï¸ Deploy to Stella IT Accounts Production

on:
  push:
    branches: [ main ]
    paths:
      - "src/**/*.ts"

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x, 14.x]

    steps:
    - name: ğŸš§ Checkout repository
      uses: actions/checkout@v2
    - name: ğŸš§ Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: ğŸš§ Installing Yarn
      run: npm install -g yarn
    - name: ğŸ—„ï¸ Cache Node Modules
      uses: actions/cache@v2
      with:
        path: |
          ~/cache
          !~/cache/exclude
          **/node_modules
        key: ${{ runner.os }}-node_modules-${{ hashFiles('**/yarn.lock') }}
    - name: ğŸ“¥ Installing dependencies
      run: yarn
    - name: ğŸ—ï¸ Generate Prisma Typescript d.ts
      run: yarn generate
    - name: ğŸ—ï¸ Build Typescript
      run: yarn build
    - name: ğŸ” Linting TypeScript/JavaScript Code
      run: yarn eslint ./src/ --ext .js,.jsx,.ts,.tsx
      