# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: ğŸ—ï¸ Deploy to Stella IT Accounts (Production)

on:
  workflow_dispatch:

  release:
    types: [created]

jobs:
  build:

    runs-on: ubuntu-latest
    environment: Stella IT Accounts Deployment
    steps:
    - name: ğŸš§ Checkout repository
      uses: actions/checkout@v2
    - name: ğŸš§ Use Node.js 14.x
      uses: actions/setup-node@v1
      with:
        node-version: 14.x
    - name: ğŸš§ Installing Yarn
      run: npm install -g yarn
    - name: ğŸ—„ï¸ Cache Node Modules
      uses: actions/cache@v2
      with:
        path: |
          ~/cache
          !~/cache/exclude
          **/node_modules
        key: ${{ runner.os }}-node_modules-${{ hashFiles('**/yarn.lock') }}
    - name: ğŸ“¥ Installing dependencies
      run: |
        yarn
        npm i -g pm2
    - name: ğŸ—ï¸ Generate Prisma Typescript d.ts
      run: yarn generate
    - name: ğŸ—ï¸ Build Typescript
      run: yarn build
    - name: ğŸŒ Setting up deploy env variables
      run: node ./.github/workflows-files/get-dotenv-from-base64.js
      env:
        DEPLOY_ENV_BASE64: ${{ secrets.S4AIT_DEPLOY_ENV_BASE64 }}
    - name: ğŸ•µï¸ Run Debug script for .env file
      run: node ./.github/workflows-files/env-deploy-validator.js
    - name: ğŸ”’ Setting up deploy key
      run: node ./.github/workflows-files/setup-key-from-base64.js
      env:
        DEPLOY_PRODUCTION_KEY_BASE64: ${{ secrets.S4AIT_DEPLOY_KEY_BASE64 }}
        DEPLOY_PRODUCTION_KEY_PATH: '~/.ssh/id_rsa'
    - name: ğŸ”’ Checking deploy key
      run: |
        ssh-keygen -l -f $DEPLOY_PRODUCTION_KEY_PATH
        ssh-add $DEPLOY_PRODUCTION_KEY_PATH
      env:
        DEPLOY_PRODUCTION_KEY_PATH: '~/.ssh/id_rsa'
    - name: ğŸš§ Deploying to production
      run: pm2 deploy production
      env:
        DEPLOY_PRODUCTION_HOST: ${{ secrets.S4AIT_DEPLOY_TARGET }}
