# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: ðŸ—ï¸ Deploy to Stella IT Accounts Production

on:
  workflow_dispatch:
  push:
    branches: [ main ]
#    paths:
#      - "src/**/*.ts"
#  release:
#    types: [created]

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
    - name: ðŸš§ Checkout repository
      uses: actions/checkout@v2
    - name: ðŸš§ Use Node.js 14.x
      uses: actions/setup-node@v1
      with:
        node-version: 14.x
    - name: ðŸš§ Installing Yarn
      run: npm install -g yarn
    - name: ðŸ—„ï¸ Cache Node Modules
      uses: actions/cache@v2
      with:
        path: |
          ~/cache
          !~/cache/exclude
          **/node_modules
        key: ${{ runner.os }}-node_modules-${{ hashFiles('**/yarn.lock') }}
    - name: ðŸ“¥ Installing dependencies
      run: |
        yarn
        yarn global add pm2
    - name: ðŸ—ï¸ Generate Prisma Typescript d.ts
      run: yarn generate
    - name: ðŸ—ï¸ Build Typescript
      run: yarn build
    - name: ðŸŒ Setting up deploy env variables
      run: echo $DEPLOY_ENV > ./.env
      env:
        DEPLOY_ENV: ${{ secrets.S4AIT_DEPLOY_ENV }}
    - name: ðŸ•µï¸ Run Debug script for .env file
      run: node ./.github/workflows-files/env-deploy-validator.js
    - name: ðŸ”’ Setting up deploy key
      run: mkdir ~/.ssh && echo $DEPLOY_KEY > ~/.ssh/id_rsa_deploy
      env:
        DEPLOY_KEY: ${{ secrets.S4AIT_DEPLOY_KEY }}
    - name: ðŸ”’ Setting up SSH config
      run: |
        PWD=`pwd`
        echo "Host \"meiling-deploy\"\n  HostName ${DEPLOY_TARGET}\n  Port 22\n  IdentityFile ${HOME}/.ssh/id_rsa_deploy" > ~/.ssh/config
      env:
        DEPLOY_TARGET: ${{ secrets.S4AIT_DEPLOY_TARGET }}
    - name: ðŸš§ Deploying to production
      run: pm2 deploy production
      env:
        DEPLOY_PRODUCTION_USER: 'root'
        DEPLOY_PRODUCTION_HOST: 'meiling-deploy'
      
